### ISSUE TITLE
A problem about warping 

### ISSUE THREAD

**Issue by shangwei5** [askerlee/craft#1]
Hi @askerlee  , nice work for Optical Flow estimation. 
There are some problems when using optical flow for warping, I try to use  flow_viz.warp_flow in your code for warping, but got the following result:
![044005-craft-f2full-kitti-12_warped](https://user-images.githubusercontent.com/43960503/162753763-14029d44-30ea-4d2b-8d2b-3995e9d68239.png)
What may be the problem? Look forward to your reply.

**Comment by askerlee** [comment]
Thanks for your interest. The flow_viz code is inherited from the gma code base, and I haven't had close look into it. Will examine what's the problem.

**Comment by shangwei5** [comment]
Ok, thank you for replying.
