### ISSUE TITLE
Visualize Optical Flow given two images

### ISSUE THREAD

**Issue by SuperBruceJia** [askerlee/craft#2]
Dear authors,

Thanks a lot for your excellent work! It helps a lot.

**How to visualize the optical flow given two consecutive images?** 
For example, given these two images (https://github.com/askerlee/craft/tree/main/imgs).

Thanks in advance, and have a nice day.

Best,

Shuyue
May 20, 2022

**Comment by SuperBruceJia** [comment]
Dear,

I followed the visualization instruction, but an error occurred as following,

```
(pytorch) ----------------------------------------------------------------------------------------------------------------------------------------------------------
~/Desktop/Codes/craft (main*) » python3 attvis.py --model craft --img1 /Users/shuyuej/Desktop/Codes/craft/imgs/frame_0047.png --img2 /Users/shuyuej/Desktop/Codes/craft/imgs/frame_0048.png --points 16,160.32,280 --att checkpoints/craft-things.pth
16, 160 => 2, 20
Traceback (most recent call last):
  File "attvis.py", line 143, in <module>
    args.radius, args.box_radius, args.img_scale, args.alpha, args.savedir, args.proj_img2)
  File "attvis.py", line 66, in vis_attention
    attention = attention5d[0, h, w].numpy()
KeyError: (0, 20, 2)
```

I tried to change the trained models or the parameters of the points, but it still cannot work. 

I appreciate your help.

Best,

Shuyue
May 20, 2022

**Comment by askerlee** [comment]
Sorry attvis.py is for visualization of transformer attentions. The usage is a bit complex. 
To generate flow between two images, please run
`python3 evaluate.py --model trained-model.pth --img1 frame1.png --img2 frame2.png --output output_directory`

**Comment by SuperBruceJia** [comment]
> Sorry attvis.py is for visualization of transformer attentions. The usage is a bit complex. To generate flow between two images, please run `python3 evaluate.py --model trained-model.pth --img1 frame1.png --img2 frame2.png --output output_directory`

Dear,

It's working now and many thanks! The models here(https://github.com/askerlee/craft/tree/main/checkpoints) are the trained model, right?

Thanks again, and have a good day.

Best regards,

Shuyue
May 20, 2022

**Comment by askerlee** [comment]
Yes these are trained models. I'd recommend to use [craft-sintel.pth](https://github.com/askerlee/craft/blob/main/checkpoints/craft-sintel.pth).

**Comment by SuperBruceJia** [comment]
> Yes these are trained models. I'd recommend to use [craft-sintel.pth](https://github.com/askerlee/craft/blob/main/checkpoints/craft-sintel.pth).

Dear,

Well received with thanks.

Best,

Shuyue
May 20, 2022

**Comment by SuperBruceJia** [comment]
Dear,

I tried to make a superior flow map using the [craft-sintel.pth](https://github.com/askerlee/craft/blob/main/checkpoints/craft-sintel.pth) model. Is there any mistake in my instructions as the generated map was not good enough? 

**Image 1**:
![frame_0047](https://user-images.githubusercontent.com/31528604/169731481-a927062d-6ae7-4e85-9494-8bbe902eb9f6.png)

**Image 2**:
![frame_0048](https://user-images.githubusercontent.com/31528604/169731507-0e49d4bb-8864-4075-a712-637d88dc7c3e.png)

**Generated flow map**:
![frame_0047-craft-f2full-sintel-12-00](https://user-images.githubusercontent.com/31528604/169731573-50b9c9e6-3e02-45f1-b28b-b9aec5253720.png)

```shell
~/Desktop/Codes/craft (main*) » python3 evaluate.py --model checkpoints/craft-sintel.pth --img1 /Users/shuyuej/Desktop/Codes/craft/imgs/frame_0047.png --img2 /Users/shuyuej/Desktop/Codes/craft/imgs/frame_0048.png --output /Users/shuyuej/Desktop
Args:
Namespace(batch_size=1, calc_flop=False, corr_radius=4, craft=False, dataset=None, dstype='both', f1trans='none', f2_attn_mask_radius=-1, f2_num_modes=4, f2_pos_code_weight=0.5, f2trans='full', fix=False, flow=None, img1='/Users/shuyuej/Desktop/Codes/craft/imgs/frame_0047.png', img2='/Users/shuyuej/Desktop/Codes/craft/imgs/frame_0048.png', inter_num_modes=4, inter_pos_code_type='bias', inter_pos_code_weight=0.5, inter_qk_have_bias=True, intra_num_modes=4, intra_pos_code_type='bias', intra_pos_code_weight=1.0, iters=12, max_val_count=-1, mixed_precision=True, model='checkpoints/craft-sintel.pth', model_name=None, nogma=False, num_heads=1, num_sofi_loops=2, output='/Users/shuyuej/Desktop', pos_bias_radius=7, position_and_content=False, position_only=False, raft=False, scale=1, seg_interval=-1, slowset=None, sofi=False, sofi_mode='dual', split='test', submit=False, test_mode=1, use_setrans=False, verbose=False, vis=False, x_shifts=None, y_shifts=None)
Lookup radius: 4
F2 transformer-out_trans: v_has_bias: False, has_FFN: False, has_input_skip: True
F2 transformer: in_feat_dim: 256, feat_dim: 256, modes: 4, qk_have_bias: False
Positional biases weight: 0.5
/Users/shuyuej/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Sliding-window Positional Biases, r: 7, max size: (200, 200)
F2-trans config:
{'feat_dim': 256, 'in_feat_dim': 256, 'pos_dim': 2, 'pos_code_weight': 0.5, 'num_modes': 4, 'tie_qk_scheme': None, 'trans_output_type': 'private', 'act_fun': <function gelu at 0x7fc56a6cd730>, 'attn_clip': 100, 'attn_diag_cycles': 1000, 'base_initializer_range': 0.02, 'qk_have_bias': False, 'v_has_bias': False, 'query_idbias_scale': 10, 'feattrans_lin1_idbias_scale': 10, 'pool_modes_feat': 'softmax', 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.2, 'drop_path_prob': 0, 'pos_code_type': 'bias', 'ablate_multihead': False, 'out_attn_probs_only': False, 'out_attn_scores_only': False, 'attn_mask_radius': -1, 'pos_bias_radius': 7, 'has_input_skip': True, 'has_FFN': False}
Model checkpoint loaded from checkpoints/craft-sintel.pth: _IncompatibleKeys(missing_keys=['module.att.to_qk.weight', 'module.att.pos_emb.rel_ind', 'module.att.pos_emb.rel_height.weight', 'module.att.pos_emb.rel_width.weight', 'module.update_block.aggregator.gamma', 'module.update_block.aggregator.to_v.weight'], unexpected_keys=['module.corr_fn.setrans.query.weight', 'module.corr_fn.setrans.query.bias', 'module.corr_fn.setrans.key.weight', 'module.corr_fn.setrans.key.bias', 'module.corr_fn.setrans.attn_softaggr.feat2score.weight', 'module.corr_fn.setrans.attn_softaggr.feat2score.bias', 'module.corr_fn.vispos_encoder.pos_coder.biases', 'module.att.setrans.query.weight', 'module.att.setrans.key.weight', 'module.att.setrans.attn_softaggr.feat2score.weight', 'module.att.setrans.attn_softaggr.feat2score.bias', 'module.att.vispos_encoder.pos_coder.biases', 'module.update_block.aggregator.input_skip_coeff', 'module.update_block.aggregator.first_linear.weight', 'module.update_block.aggregator.feat_softaggr.feat2score.weight', 'module.update_block.aggregator.feat_softaggr.feat2score.bias']).
/Users/shuyuej/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Generated flow /Users/shuyuej/Desktop/frame_0047-craft-f2full-sintel-12-00.png.
```

Thanks a lot for your reply.

Best,

Shuyue
May 23, 2022

**Comment by askerlee** [comment]
The model weights are not loaded correctly. For craft models, please specify 
--craft --setrans --f2trans full

**Comment by SuperBruceJia** [comment]
> The model weights are not loaded correctly. For craft models, please specify --craft --setrans --f2trans full

Thanks a lot for the quick response. It's working now!
![frame_0047-craft-f2full-sintel-12-00](https://user-images.githubusercontent.com/31528604/169733413-4fe20879-30b9-4582-aa6e-4ca6ce6a3615.png)

Best,

Shuyue
May 23, 2022
