### ISSUE TITLE
Question about C + T / Autoflow model

### ISSUE THREAD

**Issue by userb2020** [askerlee/craft#5]
Hello, @askerlee!
Thank you for sharing this wonderful work!

I have a question about CRAFT in Table 1 of C + T / Autoflow.
There are two commands when training CRAFT (train-craft-f2full.sh), so I do not know what command should I use to obtain the performance in Table 1.
Specifically, between these below two commands.

1. python3 train.py --name craft-things --stage things --validation sintel --output results/things/craft-f2full --restore_ckpt results/chairs/craft-f2full/craft-chairs.pth --num_steps 120000 --lr 0.000125 --image_size 400 720 --wdecay 0.0001 --gpus 0 1 --batch_size 6 --val_freq 10000 --print_freq 100 --mixed_precision --craft --f2 full --setrans

2. python3 train.py --name craft-autoflow --stage autoflow --validation sintel --output results/autoflow/craft-f2full --num_steps 200000 --lr 0.000125 --image_size 488 576 --wdecay 0.0001 --gpus 0 1 --batch_size 6 --val_freq 10000 --print_freq 100 --mixed_precision --craft --f2 full --setrans

Thanks in advance!

**Comment by askerlee** [comment]
The results in the paper were obtained by using command 1. Command 2 is an alternative model which performs slightly worse than using 1.

**Comment by userb2020** [comment]
Many thanks for quick reply!
